
modLoader="javafml" #mandatory

loaderVersion="[33,)" 

license="All rights reserved"

issueTrackerURL="https://github.com/saksham4106/FallDamageBegone/issues" #optional

[[mods]] #mandatory

modId="nofalldamage" #mandatory

version="${file.jarVersion}" #mandatory

displayName="FallDamageBegone Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="The credits of this mod goes to JAVA and Pau#6435 because he asked me to make it" #optional

authors="Saksham Kumar" #optional

description='''
This mod will disable fall damage for all mobs but not for you
'''

